"""demo_stream.py -- live-streaming DEMO/TEST harness for the ECG pipeline.

Feeds a signal (synthetic, from synthetic_ecg.py, OR a real recording file)
through the EXISTING pipeline in simulated real time -- in chunks, as if
arriving live from a patch -- printing the evolving state (beats so far,
rhythm findings so far, current risk level) after each chunk arrives.

This module reuses the existing pipeline stages UNCHANGED:
  - `ecg_pipeline_core.ECGPipeline.run()` for beat detection/classification/
    rhythm analysis/risk scoring (run again, from scratch, on the
    cumulative signal received so far -- the pipeline itself has no
    incremental/streaming mode, so "streaming" here means re-running the
    whole deterministic pipeline on a growing prefix, not re-implementing
    any of its stages).
  - `agent_bridge.build_risk_report_json()` for the per-chunk status
    (already implements the NOT_ASSESSABLE / MIN_BEATS_FOR_ASSESSMENT
    guard, so an early chunk with too little signal is correctly reported
    as not-yet-assessable rather than a misleading "clean" LOW).
  - `agent_bridge.run_full_report()` for the ONE final complete report +
    MedGemma narrative (or its deterministic fallback if Ollama is down --
    this module never starts/installs an Ollama server, it only asks
    run_full_report, which already degrades gracefully on its own).

It is an input/orchestration wrapper only -- no classifier, threshold,
AAMI-scheme, or risk-cascade code is touched or reimplemented here.

============================================================================
SYNTHETIC LABELING (Hard Boundary -- see synthetic_ecg.py)
============================================================================
Any report produced from a synthetic recording is saved under
data/reports/synthetic/<scenario>/, with report_json["source"] set to
"synthetic", report_json["ground_truth"] populated from the generator's
GroundTruth, and a "SYNTHETIC -- not a real patient" banner prepended to
the saved .md file -- so it can never be mistaken for a real patient
result. This module never adds synthetic output to any training set,
DS1/DS2 split, or classifier metric.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from ecg_pipeline import agent_bridge
from ecg_pipeline.ecg_pipeline_core import (
    DATA_RAW, ECGPipeline, FiveClassBeatClassifier, MODELS_DIR, PipelineResult, Recording,
    TARGET_FS, apply_filter_chain, parse_vitalpatch_ecg, parse_wfdb_record, run_sqi_gate, to_target_rate,
)
from ecg_pipeline.synthetic_ecg import SCENARIOS, GroundTruth, generate_scenario

DATA_REPORTS_SYNTHETIC = DATA_RAW.parent / "reports" / "synthetic"
DEFAULT_LIVE_HTML = DATA_RAW.parent / "reports_ui" / "live.html"

# Kept in sync with report_ui.py's own copies (duplicated, not imported, to
# avoid a circular import: report_ui.py imports build_waveform_block from
# this module).
RISK_COLORS = {
    "LOW": "#2e7d32", "MEDIUM": "#f9a825", "HIGH": "#ef6c00",
    "CRITICAL": "#c62828", "NOT_ASSESSABLE": "#616161",
}
CLASS_COLORS = {"N": "#2e7d32", "S": "#1565c0", "V": "#c62828", "F": "#8e24aa", "Q": "#9e9e9e"}

SYNTHETIC_BANNER = (
    "> **SYNTHETIC -- NOT A REAL PATIENT.** This recording was generated by "
    "`ecg_pipeline/synthetic_ecg.py` for pipeline demo/testing purposes only. "
    "It must never be used to train, retrain, or evaluate the beat classifier, "
    "and it does not describe any real person.\n"
)


def _sub_recording(recording: Recording, n_samples: int) -> Recording:
    """A read-only view of the first `n_samples` of `recording`, as a
    Recording object, so ECGPipeline.run() (which only accepts a
    Recording) can be called on the "signal received so far" without any
    change to ECGPipeline itself."""
    return Recording(
        signal_mv=recording.signal_mv[:n_samples],
        timestamps_ms=recording.timestamps_ms[:n_samples],
        fs_nominal=recording.fs_nominal,
        source=recording.source,
        patient_id=recording.patient_id,
        segment_id=recording.segment_id,
        gaps=[g for g in recording.gaps if g[1] <= n_samples],
        already_bandpass_filtered=recording.already_bandpass_filtered,
        meta=recording.meta,
    )


def _render_live_html(partial: Recording, filtered: np.ndarray, result: PipelineResult,
                       report_json: dict, chunk_i: int, n_chunks: int, n_total_samples: int,
                       out_path: Path, refresh_seconds: float) -> None:
    """Writes (overwrites in place) one HTML page with two stacked plots --
    the RAW signal received so far, and the PREPROCESSED (filtered,
    TARGET_FS-resampled) signal the pipeline actually analyzes, with beats
    colored by class -- plus the current risk/rhythm status. The page
    <meta refresh>'es itself, so opening it once in a browser and leaving
    it open shows the stream progressing live as this function keeps
    overwriting the same file each chunk."""
    fs_raw = partial.fs_nominal
    raw = partial.signal_mv
    t_raw = np.arange(len(raw)) / fs_raw
    t_filt = np.arange(len(filtered)) / TARGET_FS

    fig, axes = plt.subplots(2, 1, figsize=(9, 5.5), dpi=120)
    axes[0].plot(t_raw, raw, color="#455a64", linewidth=0.5)
    axes[0].set_title(f"RAW ECG as received from device (fs={fs_raw:g}Hz)")
    axes[0].set_ylabel("raw amplitude")
    axes[0].set_xlim(0, n_total_samples / fs_raw)

    axes[1].plot(t_filt, filtered, color="#37474f", linewidth=0.6, zorder=1)
    seen = set()
    for b, lbl in zip(result.beats, result.beat_labels):
        if b.quality_rejected:
            continue
        idx = int(round(b.r_peak_ms / 1000.0 * TARGET_FS))
        if not (0 <= idx < len(filtered)):
            continue
        color = CLASS_COLORS.get(lbl, "#000000")
        axes[1].scatter([b.r_peak_ms / 1000.0], [filtered[idx]], color=color, s=14, zorder=3,
                        label=(lbl if lbl not in seen else None))
        seen.add(lbl)
    axes[1].set_title(f"PREPROCESSED ECG (filtered, resampled to {TARGET_FS:g}Hz -- what the pipeline analyzes)")
    axes[1].set_xlabel("time (s)")
    axes[1].set_ylabel("filtered amplitude")
    axes[1].set_xlim(0, n_total_samples / fs_raw)
    if seen:
        axes[1].legend(loc="upper right", fontsize=7, ncol=len(seen), frameon=False)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    png_b64 = base64.b64encode(buf.getvalue()).decode("ascii")

    risk = report_json["risk_level"]
    rhythm_kinds = sorted({f["kind"] for f in report_json["rhythm_findings"]})
    done = chunk_i >= n_chunks
    refresh_tag = "" if done else f'<meta http-equiv="refresh" content="{refresh_seconds}">'
    html = f"""<!doctype html>
<html><head><meta charset="utf-8">{refresh_tag}
<title>LIVE ECG stream</title>
<style>
body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 1.5rem; background: #fafafa; }}
.pill {{ display:inline-block; padding:.3rem .9rem; border-radius:999px; color:#fff; font-weight:bold;
         background:{RISK_COLORS.get(risk, '#455a64')}; }}
img {{ max-width: 100%; }}
</style></head>
<body>
<h2>LIVE ECG stream -- {partial.source}/{partial.patient_id}/{partial.segment_id}</h2>
<p>Chunk {chunk_i}/{n_chunks} &nbsp; Risk so far: <span class="pill">{risk}</span>
&nbsp; Rhythm findings so far: {', '.join(rhythm_kinds) or '(none)'}
&nbsp; Beats analyzed: {report_json['recording']['n_beats_analyzed']}</p>
<img src="data:image/png;base64,{png_b64}" alt="live ECG plot"/>
<p><small>{'Stream complete -- this page will not refresh further.' if done else
           f'Auto-refreshes every {refresh_seconds:g}s -- leave this tab open.'}</small></p>
</body></html>
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html)


def stream_recording(recording: Recording, classifier: FiveClassBeatClassifier,
                      chunk_seconds: float = 5.0, speed: float = 8.0,
                      quiet: bool = False, live_html: Path | None = None,
                      live_refresh_seconds: float = 2.0) -> None:
    """Feeds `recording` through the pipeline in `chunk_seconds`-sized
    chunks, sleeping `chunk_seconds / speed` between chunks (speed<=0 ->
    no sleep, run as fast as possible) and printing the evolving state
    after each one. If `live_html` is given, also (re)writes a self-
    refreshing HTML page there each chunk showing the raw vs preprocessed
    waveform so far (see _render_live_html) -- open it once in a browser
    and leave it open to watch the stream live. Does not return anything
    -- callers should follow this with a single
    agent_bridge.run_full_report() call on the complete `recording` for
    the final saved report.
    """
    fs = recording.fs_nominal
    chunk_samples = max(1, int(round(chunk_seconds * fs)))
    n_total = len(recording.signal_mv)
    n_chunks = max(1, int(np.ceil(n_total / chunk_samples)))

    if not quiet:
        print(f"--- LIVE STREAM: {recording.source}/{recording.patient_id}/{recording.segment_id} "
              f"({n_total} samples @ {fs}Hz = {n_total / fs:.1f}s) ---")
        print(f"    chunk_seconds={chunk_seconds}  speed={speed}x  "
              f"({'no sleep, as fast as possible' if speed <= 0 else f'{chunk_seconds / speed:.2f}s sleep/chunk'})")
        if live_html is not None:
            print(f"    live view -> file://{Path(live_html).resolve()}  (open now, it will update in place)")

    for i in range(1, n_chunks + 1):
        n_so_far = min(i * chunk_samples, n_total)
        partial = _sub_recording(recording, n_so_far)
        pipeline = ECGPipeline(classifier=classifier)
        result = pipeline.run(partial)
        report_json = agent_bridge.build_risk_report_json(result)

        rhythm_kinds = sorted({f["kind"] for f in report_json["rhythm_findings"]})
        if not quiet:
            print(f"[t={n_so_far / fs:6.1f}s] chunk {i:>3}/{n_chunks} | "
                  f"beats detected/analyzed={report_json['recording']['n_beats_detected']:>4}/"
                  f"{report_json['recording']['n_beats_analyzed']:>4} | "
                  f"rhythm_so_far={rhythm_kinds or '[]'} | "
                  f"risk_so_far={report_json['risk_level']}")

        if live_html is not None:
            filtered = compute_filtered_signal(partial)
            _render_live_html(partial, filtered, result, report_json, i, n_chunks, n_total,
                               Path(live_html), live_refresh_seconds)

        if speed > 0 and i < n_chunks:
            time.sleep(chunk_seconds / speed)

    if not quiet:
        print("--- stream complete, producing final full report ---")


def _prepend_banner(markdown: str) -> str:
    return SYNTHETIC_BANNER + "\n" + markdown


def compute_filtered_signal(recording: Recording) -> np.ndarray:
    """Recomputes the continuous filtered signal ECGPipeline.run() analyzes
    (its Stages 1-4: SQI gate -> resample to TARGET_FS -> filter chain),
    using the SAME already-public functions ECGPipeline.run() itself calls
    -- not a new preprocessing path. This value isn't part of
    PipelineResult today (only per-beat windows are), so report_ui.py
    needs it recomputed for waveform plotting; this helper is shared so
    both the synthetic save path here and report_ui's real-recording
    reconstruction path use the identical, unmodified stage sequence."""
    keep_mask, _verdicts = run_sqi_gate(recording.signal_mv, recording.timestamps_ms, recording.fs_nominal)
    signal_clean = recording.signal_mv.copy()
    signal_clean[~keep_mask] = np.nan
    resampled, t_resampled = to_target_rate(signal_clean, recording.timestamps_ms, recording.fs_nominal, TARGET_FS)
    valid = ~np.isnan(resampled)
    if len(resampled) == 0 or not valid.any():
        return np.array([])
    filled = np.interp(t_resampled, t_resampled[valid], resampled[valid])
    return apply_filter_chain(filled, TARGET_FS, already_bandpass_filtered=recording.already_bandpass_filtered)


def build_waveform_block(recording: Recording, result: PipelineResult) -> dict:
    """The extra data report_ui.py needs to plot a waveform with per-beat
    class markers that isn't in agent_bridge's report JSON today: the
    continuous analyzed signal, and each analyzed beat's R-peak time +
    class label. Uses only already-computed PipelineResult fields (beats,
    beat_labels) plus the recomputed Stage 1-4 signal above -- no
    reclassification, no new detection."""
    filtered = compute_filtered_signal(recording)
    beats = [{"r_peak_ms": b.r_peak_ms, "label": lbl, "quality_rejected": b.quality_rejected}
             for b, lbl in zip(result.beats, result.beat_labels)]
    return {"fs": TARGET_FS, "signal": [round(float(x), 4) for x in filtered.tolist()], "beats": beats}


def save_synthetic_report(report_json: dict, ground_truth: GroundTruth, recording: Recording,
                           result: PipelineResult,
                           out_root: Path = DATA_REPORTS_SYNTHETIC) -> tuple[Path, Path]:
    """Saves a synthetic report with unambiguous synthetic labeling: a
    dedicated synthetic/<scenario>/ subfolder, source="synthetic" and a
    ground_truth block in the JSON, and a banner prepended to the .md.
    Does not touch agent_bridge.save_report() or its output format for
    real recordings -- this is a separate, additive save path used only
    for synthetic scenarios. Also embeds a "waveform" block (see
    build_waveform_block) so report_ui.py can plot this recording without
    needing to regenerate/re-run anything.
    """
    report_json = dict(report_json)
    report_json["source"] = "synthetic"
    report_json["synthetic"] = True
    report_json["ground_truth"] = asdict(ground_truth)
    report_json["waveform"] = build_waveform_block(recording, result)

    out_dir = out_root / ground_truth.scenario
    out_dir.mkdir(parents=True, exist_ok=True)
    segment_id = report_json["recording"]["segment_id"]

    json_path = out_dir / f"{segment_id}.json"
    md_path = out_dir / f"{segment_id}.md"
    json_path.write_text(json.dumps(report_json, indent=2, default=str))
    md_path.write_text(_prepend_banner(agent_bridge.render_report_markdown(report_json)))
    return json_path, md_path


def _load_real_recordings(source: str, path: Path) -> list[Recording]:
    if source == "vitalpatch":
        return parse_vitalpatch_ecg(path)
    if source == "wfdb":
        return [parse_wfdb_record(path)]
    raise ValueError(f"Unknown source: {source!r}")


def run_demo(scenario: str | None, file: Path | None, source: str | None,
             classifier_path: Path, chunk_seconds: float, speed: float,
             duration_s: float | None, fs: float | None, seed: int | None,
             out_root: Path, quiet: bool = False, live_html: Path | None = None,
             live_refresh_seconds: float = 2.0) -> dict:
    """Runs one full demo: generate/load -> stream -> final full report ->
    save. Returns the final report_json (with the narrative attached)."""
    classifier = FiveClassBeatClassifier()
    classifier.load(classifier_path)

    ground_truth = None
    if scenario is not None:
        kwargs = {}
        if duration_s is not None:
            kwargs["duration_s"] = duration_s
        if fs is not None:
            kwargs["fs"] = fs
        if seed is not None:
            kwargs["seed"] = seed
        recording, ground_truth = generate_scenario(scenario, **kwargs)
    else:
        recordings = _load_real_recordings(source, file)
        if not recordings:
            raise RuntimeError(f"No recordings parsed from {file} (source={source})")
        recording = recordings[0]

    stream_recording(recording, classifier, chunk_seconds=chunk_seconds, speed=speed, quiet=quiet,
                      live_html=live_html, live_refresh_seconds=live_refresh_seconds)

    report_json, result = agent_bridge.run_full_report(recording, classifier)

    if ground_truth is not None:
        json_path, md_path = save_synthetic_report(report_json, ground_truth, recording, result, out_root=out_root)
    else:
        out_dir = out_root
        out_dir.mkdir(parents=True, exist_ok=True)
        json_path, md_path = agent_bridge.save_report(report_json, out_dir, recording.segment_id)

    if not quiet:
        print(f"\nFinal risk level: {report_json['final_risk_level']}")
        print(f"MedGemma status:  {report_json['medgemma']['status']}")
        print(f"Saved -> {json_path}")
        print(f"Saved -> {md_path}")

    report_json["_saved_json_path"] = str(json_path)
    report_json["_saved_md_path"] = str(md_path)
    return report_json


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--scenario", choices=SCENARIOS, help="synthetic scenario (see synthetic_ecg.py)")
    src.add_argument("--file", type=Path, help="a real recording file to stream instead of synthetic")
    parser.add_argument("--source", choices=["vitalpatch", "wfdb"], help="required if --file is given")
    parser.add_argument("--classifier", type=Path, default=MODELS_DIR / "five_class_xgb.json")
    parser.add_argument("--chunk-seconds", type=float, default=5.0)
    parser.add_argument("--speed", type=float, default=8.0,
                         help="playback speed multiplier; 1.0 = true real time, <=0 = no sleep (instant)")
    parser.add_argument("--duration-s", type=float, default=None, help="synthetic only: override scenario duration")
    parser.add_argument("--fs", type=float, default=None, help="synthetic only: override sample rate (Hz)")
    parser.add_argument("--seed", type=int, default=None, help="synthetic only: override random seed")
    parser.add_argument("--out-root", type=Path, default=None,
                         help="where to save the report (default: data/reports/synthetic/<scenario>/ for "
                              "synthetic, data/reports/demo_stream/ for --file)")
    parser.add_argument("--quiet", action="store_true", help="suppress the live per-chunk printout")
    parser.add_argument("--live", action="store_true",
                         help="also write a self-refreshing HTML page (raw ECG + preprocessed ECG, updated "
                              "every chunk) -- open it in a browser once and leave it open to watch live")
    parser.add_argument("--live-out", type=Path, default=DEFAULT_LIVE_HTML,
                         help=f"path for the live HTML page (default: {DEFAULT_LIVE_HTML})")
    parser.add_argument("--live-refresh-seconds", type=float, default=2.0,
                         help="how often the live page's <meta refresh> reloads")
    args = parser.parse_args(argv)

    if args.file is not None and args.source is None:
        parser.error("--source is required when --file is given")

    out_root = args.out_root or (DATA_REPORTS_SYNTHETIC if args.scenario else DATA_RAW.parent / "reports" / "demo_stream")
    live_html = args.live_out if args.live else None

    run_demo(args.scenario, args.file, args.source, args.classifier, args.chunk_seconds, args.speed,
              args.duration_s, args.fs, args.seed, out_root, quiet=args.quiet,
              live_html=live_html, live_refresh_seconds=args.live_refresh_seconds)


if __name__ == "__main__":
    main()
